name:                curl-runnings
version:             0.5.1
github:              aviaviavi/curl-runnings
license:             MIT
author:              Avi Press
maintainer:          mail@avi.press
copyright:           2018 Avi Press
category:            Testing
synopsis:            A framework for declaratively writing curl based API tests

extra-source-files:
- README.md
- examples/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/aviaviavi/curl-runnings#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Testing.CurlRunnings
  - Testing.CurlRunnings.Types
  - Testing.CurlRunnings.Internal
  - Testing.CurlRunnings.Internal.Parser
  dependencies:
  - aeson >=1.2.4.0
  - aeson-pretty >=0.8.5
  - bytestring >=0.10.8.2
  - case-insensitive >=0.2.1
  - directory >=1.3.0.2
  - hspec >= 2.4.4
  - hspec-expectations >=0.8.2
  - http-conduit >=2.2.4
  - http-types >=0.9.1
  - megaparsec >=6.3.0
  - text >=1.2.2.2
  - unordered-containers >=0.2.8.0
  - vector >=0.12.0
  - yaml >=0.8.28

executables:
  curl-runnings:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.7
    - cmdargs >=0.10.20
    - curl-runnings
    - text >=1.2.2.2

tests:
  curl-runnings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curl-runnings
    - directory >=1.3.0.2
    - hspec >= 2.4.4
    - hspec-expectations >=0.8.2
