name:                curl-runnings
version:             0.1.0
github:              aviaviavi/curl-runnings
license:             MIT
author:              Avi Press
maintainer:          mail@avi.press
copyright:           2018 Avi Press
category:            Testing
synopsis:            A framework for declaratively writing curl based API tests

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/aviaviavi/curl-runnings#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Testing.CurlRunnings
  - Testing.CurlRunnings.Types
  - Testing.CurlRunnings.Internal
  dependencies:
  - aeson >=1.2.4.0 && <1.3
  - aeson-pretty >=0.8.5 && <0.9
  - bytestring >=0.10.8.2 && <0.11
  - http-conduit >=2.2.4 && <2.3
  - text >=1.2.2.2 && <1.3
  - unordered-containers >=0.2.8.0 && <0.3

executables:
  curl-runnings:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson >=1.2.4.0 && <1.3
    - base >=4.7 && <5
    - bytestring >=0.10.8.2 && <0.11
    - cmdargs >=0.10.20 && <0.11
    - curl-runnings
    - text >=1.2.2.2 && <1.3
    - yaml >=0.8.28 && < 0.9

tests:
  curl-runnings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curl-runnings
